git_hash: 3e8bbdd821af094a2183fa78fdc74f78834f71fb
model_class: TimeDistributedEfficientNet
species:
- blank
starting_learning_rate: 0.001
train_config:
  auto_lr_find: false
  backbone_finetune_config:
    backbone_initial_ratio_lr: 0.01
    multiplier: 1
    pre_train_bn: true
    train_bn: false
    unfreeze_backbone_at_epoch: 3
    verbose: true
  batch_size: 4
  checkpoint: null
  data_dir: ''
  dry_run: false
  early_stopping_config:
    mode: max
    monitor: val_macro_f1
    patience: 5
    verbose: true
  from_scratch: true
  gpus: 1
  max_epochs: null
  model_cache_dir: /home/ubuntu/.cache/zamba
  model_name: time_distributed
  num_workers: 2
  overwrite: false
  predict_all_zamba_species: true
  save_dir: /home/ubuntu/pjmf-zamba
  scheduler_config:
    scheduler: MultiStepLR
    scheduler_params:
      gamma: 0.5
      milestones:
      - 3
      verbose: true
  skip_load_validation: true
  split_proportions: null
  weight_download_region: us
training_start_time: '2022-08-25T22:39:23.050198'
video_loader_config:
  cache_dir: data/zamba-cache
  cleanup_cache: false
  crop_bottom_pixels: 50
  early_bias: false
  ensure_total_frames: true
  evenly_sample_total_frames: false
  fps: 4.0
  frame_indices: null
  frame_selection_height: null
  frame_selection_width: null
  i_frames: false
  megadetector_lite_config:
    confidence: 0.25
    device: cuda
    fill_mode: score_sorted
    frame_batch_size: 24
    image_height: 640
    image_width: 640
    n_frames: 16
    nms_threshold: 0.45
    seed: 55
    sort_by_time: true
  model_input_height: 240
  model_input_width: 426
  pix_fmt: rgb24
  scene_threshold: null
  total_frames: 16
