build: false

environment:
  global:
      MINGW_64: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin
      MINICONDA: C:\Miniconda3


install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - "conda create -q -n test-environment python=3.6"
  - activate test-environment
  - conda install -c anaconda py-xgboost==0.71
  - pip install -r requirements-dev.txt
  - pip install .[cpu]

test_script:
  - python -m pytest -s zamba
  - flake8 zamba

