build: false

environment:
  matrix:
    - PYTHON_VERSION: 3.6


install:
  - pip install xgboost-0.71-cp36-cp36m-win_amd64.whl
  - pip install -r requirements-dev.txt
  - pip install .[cpu]

test_script:
  - python -m pytest -s zamba
  - flake8 zamba

