build: false

platform: x64

environment:
  matrix:
      - PYTHON_VERSION: 3.6
        MINICONDA: C:\Miniconda3-x64
        PYTHON_ARCH: "64"

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - "conda create -q -n test-environment python=3.6"
  - activate test-environment
  - pip install https://github.com/worldbank/ML-classification-algorithms-poverty/raw/master/deps/xgboost-0.71-cp36-cp36m-win_amd64.whl
  - pip install -r requirements-dev.txt
  - pip install .[cpu]

test_script:
  - python -m pytest -s zamba
  - flake8 zamba
