video_loader_config:
  model_input_height: 224
  model_input_width: 224
  crop_bottom_pixels: 50
  ensure_total_frames: True
  megadetector_lite_config:
    confidence: 0.25
    fill_mode: "score_sorted"
    n_frames: 16
  total_frames: 16


train_config:
  # data_directory: YOUR_DATA_DIRECTORY_HERE
  # labels: YOUR_LABELS_CSV_HERE
  model_name: european
  # or
  # checkpoint: YOUR_CKPT_HERE
  batch_size: 16
  num_workers: 3
  scheduler_config:
    scheduler: MultiStepLR
    scheduler_params:
      milestones: [3]
      gamma: 0.5
      verbose: True
  auto_lr_find: True
  backbone_finetune_config:
  early_stopping_config:
  max_epochs: 20


predict_config:
  # data_directory: YOUR_DATA_DIRECTORY_HERE
  # or
  # filepaths: YOUR_FILEPATH_CSV_HERE
  model_name: european
  # or
  # checkpoint: YOUR_CKPT_HERE
