video_loader_config:
  model_input_height: 224
  model_input_width: 224
  crop_bottom_pixels: 50
  ensure_total_frames: True
  megadetector_lite_config:
    confidence: 0.25
    fill_mode: "score_sorted"
    n_frames: 32
  total_frames: 32


train_config:
  # data_directory: YOUR_DATA_DIRECTORY_HERE
  # labels: YOUR_LABELS_CSV_HERE
  model_name: slowfast
  # or
  # checkpoint: YOUR_CKPT_HERE
  batch_size: 32
  num_workers: 3
  scheduler_config:
    scheduler: MultiStepLR
    scheduler_params:
      milestones: [1]
      gamma: 0.5
      verbose: True
  auto_lr_find: True
  backbone_finetune_config:
    multiplier: 10
    unfreeze_backbone_at_epoch: 1
  early_stopping_config:
    patience: 5


predict_config:
  # data_directory: YOUR_DATA_DIRECTORY_HERE
  # or
  # filepaths: YOUR_FILEPATH_CSV_HERE
  model_name: slowfast
  # or
  # checkpoint: YOUR_CKPT_HERE
