train_config:
  backbone_finetune_config:
    backbone_initial_ratio_lr: 0.01
    multiplier: 10
    pre_train_bn: false
    train_bn: false
    unfreeze_backbone_at_epoch: 3
    verbose: true
  early_stopping_config:
    mode: max
    monitor: val_macro_f1
    patience: 5
    verbose: true
  model_name: slowfast
  scheduler_config:
    scheduler: MultiStepLR
    scheduler_params:
      gamma: 0.5
      milestones:
      - 1
      verbose: true
video_loader_config:
  crop_bottom_pixels: 50
  early_bias: false
  ensure_total_frames: true
  evenly_sample_total_frames: false
  fps: 8.0
  frame_indices: null
  frame_selection_height: null
  frame_selection_width: null
  i_frames: false
  megadetector_lite_config:
    confidence: 0.25
    fill_mode: score_sorted
    image_height: 416
    image_width: 416
    n_frames: 32
    nms_threshold: 0.45
    seed: 55
    sort_by_time: true
  model_input_height: 240
  model_input_width: 426
  pix_fmt: rgb24
  scene_threshold: null
  total_frames: 32
predict_config:
  model_name: slowfast
public_checkpoint: slowfast_3c9d5d0c72.ckpt
