git_hash: edc7570a52a3c5edfa852a27cfabd7ed78a13d06
model_class: SlowFast
species:
- aardvark
- antelope_duiker
- badger
- bat
- bird
- blank
- cattle
- cheetah
- chimpanzee_bonobo
- civet_genet
- elephant
- equid
- forest_buffalo
- fox
- giraffe
- gorilla
- hare_rabbit
- hippopotamus
- hog
- human
- hyena
- large_flightless_bird
- leopard
- lion
- mongoose
- monkey_prosimian
- pangolin
- porcupine
- reptile
- rodent
- small_cat
- wild_dog_jackal
starting_learning_rate: 0.0013182567385564075
train_config:
  auto_lr_find: true
  backbone_finetune_config:
    backbone_initial_ratio_lr: 0.01
    multiplier: 10
    pre_train_bn: false
    train_bn: false
    unfreeze_backbone_at_epoch: 3
    verbose: true
  batch_size: 2
  checkpoint: null
  data_dir: /home/ubuntu/zamba-algorithms
  dry_run: false
  early_stopping_config:
    mode: max
    monitor: val_macro_f1
    patience: 5
    verbose: true
  from_scratch: true
  gpus: 1
  max_epochs: null
  model_cache_dir: /home/ubuntu/.cache/zamba
  model_name: slowfast
  num_workers: 3
  overwrite: false
  predict_all_zamba_species: true
  save_dir: experiments/slowfast_small_set_full_size_mdlite
  scheduler_config:
    scheduler: MultiStepLR
    scheduler_params:
      gamma: 0.5
      milestones:
      - 1
      verbose: true
  skip_load_validation: true
  split_proportions: null
  weight_download_region: us
training_start_time: '2021-10-19T16:43:32.866905'
video_loader_config:
  cache_dir: /tmp/zamba_cache
  cleanup_cache: false
  crop_bottom_pixels: 50
  early_bias: false
  ensure_total_frames: true
  evenly_sample_total_frames: false
  fps: 8.0
  frame_indices: null
  frame_selection_height: null
  frame_selection_width: null
  i_frames: false
  megadetector_lite_config:
    confidence: 0.25
    device: cuda
    fill_mode: score_sorted
    image_height: 416
    image_width: 416
    n_frames: 32
    nms_threshold: 0.45
    seed: 55
    sort_by_time: true
  model_input_height: 240
  model_input_width: 426
  pix_fmt: rgb24
  scene_threshold: null
  total_frames: 32
