inference_start_time: '2021-09-30T10:55:29.100719'
model_class: TimeDistributedEfficientNet
predict_config:
  batch_size: 1
  cache_dir: /home/ubuntu/.cache/zamba
  checkpoint: experiments/td_small_set_full_size_mdlite/results/version_1/time_distributed.ckpt
  data_directory: /home/ubuntu/zamba-algorithms
  dry_run: false
  gpus: 1
  model_name: time_distributed
  num_workers: 5
  output_class_names: false
  proba_threshold: null
  save: experiments/td_small_set_full_size_mdlite/results/version_1/zamba_predictions.csv
  skip_load_validation: true
  weight_download_region: us
species:
- aardvark
- antelope_duiker
- badger
- bat
- bird
- blank
- cattle
- cheetah
- chimpanzee_bonobo
- civet_genet
- elephant
- equid
- forest_buffalo
- fox
- giraffe
- gorilla
- hare_rabbit
- hippopotamus
- hog
- human
- hyena
- large_flightless_bird
- leopard
- lion
- mongoose
- monkey_prosimian
- pangolin
- porcupine
- reptile
- rodent
- small_cat
- wild_dog_jackal
video_loader_config:
  crop_bottom_pixels: 50
  early_bias: false
  ensure_total_frames: true
  evenly_sample_total_frames: false
  fps: 4.0
  frame_indices: null
  frame_selection_height: null
  frame_selection_width: null
  i_frames: false
  megadetector_lite_config:
    confidence: 0.25
    device: cuda
    fill_mode: score_sorted
    image_height: 416
    image_width: 416
    n_frames: 16
    nms_threshold: 0.45
    seed: 55
    sort_by_time: true
  model_input_height: 240
  model_input_width: 426
  pix_fmt: rgb24
  scene_threshold: null
  total_frames: 16
