name: docs-latest

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    name: Build 'latest' docs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev/docs.txt

      - name: Build documentation
        run: |
          make docs

      - name: Stage docs on gh-pages
        working-directory: docs
        run: |
          git fetch origin gh-pages --depth=1
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          mike deploy --push ~latest --title=latest

  deploy:
    name: Deploy docs to Netlify
    needs: build
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Deploy docs to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: "./"
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
