name: publish-docs

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and publish docs
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.7]

    steps:

        - uses: actions/checkout@v2
    
        - name: Set up Python ${{ matrix.python-version }} with Miniconda
          uses: goanpeca/setup-miniconda@v1
          with:
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
    
        - name: Get pip cache dir
          id: pip-cache
          shell: bash -l {0}
          run: |
            echo "::set-output name=dir::$(python -m pip cache dir)"
            
        - name: Load pip cache
          uses: actions/cache@v2
          with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ matrix.os }}-${{ matrix.python-version }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
                ${{ matrix.os }}-${{ matrix.python-version }}-pip-
    
        - name: Install ffmpeg
          shell: bash -l {0}
          run: |
            conda install -y ffmpeg
    
        - name: Install dependencies
          shell: bash -l {0}
          run: |
            make reqs

        - name: Deploy Docs
          shell: bash -l {0}
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.ZAMBA_DOCS_AWS_ACCESS_KEY }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.ZAMBA_DOCS_AWS_SECRET_KEY }}
          run: |
            make deploy-docs
