name: release

on:
  release:
    types:
      - published

jobs:
  build:
    name: Build and publish new release
    runs-on: "ubuntu-latest"

    steps:
      - name: Remove unused software
        run: |
          echo "Available storage before:"
          sudo df -h
          echo
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          echo "Available storage after:"
          sudo df -h
          echo

      - uses: actions/checkout@v4

      - name: Set up Python and uv
        uses: drivendataorg/setup-python-uv-action@v1
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          uv pip install -r requirements-dev/docs.txt
          uv pip install -e .

      - name: Check that versions match
        id: version
        run: |
          echo "Release tag: [${{ github.event.release.tag_name }}]"
          PACKAGE_VERSION=$(python -c "import zamba; print(zamba.__version__)")
          echo "Package version: [$PACKAGE_VERSION]"
          [ ${{ github.event.release.tag_name }} == "v$PACKAGE_VERSION" ] || { exit 1; }
          echo "::set-output name=major_minor_version::v${PACKAGE_VERSION%.*}"

      - name: Build package
        run: |
          uv pip install build
          make dist
          cp dist/*.tar.gz zamba.tar.gz  # rename source package so URL can be consistent

      - name: Add source package to release
        run: |
          curl \
            -H "Authorization: token ${{ github.token }}" \
            -H "Content-Type: $(file -b --mime-type zamba.tar.gz)" \
            --data-binary @zamba.tar.gz \
            $(echo "${{ github.event.release.upload_url }}" | sed "s/{?name,label}/?name=zamba.tar.gz/g")

      - name: Build docs
        run: |
          make docs

      # PUBLISHING CURRENTLY BLOCKED BY ISSUE #160
      # - name: Publish to Test PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.3.0
      #   with:
      #     user: ${{ secrets.PYPI_TEST_USERNAME }}
      #     password: ${{ secrets.PYPI_TEST_PASSWORD }}
      #     repository_url: https://test.pypi.org/legacy/
      #     skip_existing: true

      # - name: Publish to Production PyPI
      #   uses: pypa/gh-action-pypi-publish@v1.3.0
      #   with:
      #     user: ${{ secrets.PYPI_PROD_USERNAME }}
      #     password: ${{ secrets.PYPI_PROD_PASSWORD }}
      #     skip_existing: false

      - name: Stage 'stable' docs on gh-pages
        working-directory: docs
        run: |
          git fetch origin gh-pages --depth=1
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          # Rename old stable version
          mike list -j | jq
          OLD_STABLE=$(mike list -j | jq -r '.[] | select(.aliases | index("stable")) | .title' | awk '{print $1;}')
          echo $OLD_STABLE
          mike retitle stable $OLD_STABLE
          # Deploy new version as stable
          mike deploy --push --update-aliases --alias-type=copy \
            ${{ steps.version.outputs.major_minor_version }} \
            stable \
            --title="${{ github.event.release.tag_name }} (stable)"

  deploy-docs:
    name: Deploy docs to Netlify
    needs: build
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Deploy docs to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: "./"
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          overwrites-pull-request-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
